const mockJobs = [
  {
    id: "job-1",
    title: "Junior React Developer",
    company: "TechFlow Romania",
    logoBg: "from-blue-500 to-cyan-600",
    faculty: "Facultatea de Matematică și Informatică",
    description:
      "Alătură-te echipei noastre Agile pentru a construi aplicații web de ultimă generație. Vei colabora îndeaproape cu designeri UX și dezvoltatori seniori pe tehnologii ca React, TypeScript și TailwindCSS.",
    requirements: [
      "Înțelegerea fundamentală a HTML, CSS și JavaScript modern (ES6+)",
      "Experiență de bază cu framework-ul React (proiecte facultate sau personale)",
      "Utilizarea sistemelor de control al versiunilor (Git)",
      "Gândire algoritmică și dorința de a învăța concepte noi",
    ],
    location: "Cluj-Napoca (Hibrid)",
    salary: "4.800 - 6.200 RON net",
    type: "Full-time",
    tags: ["React", "TypeScript", "Tailwind", "Git"],
    date: "Acum 2 zile",
    compatibility: 95,
  },
  {
    id: "job-2",
    title: "Junior Financial Analyst",
    company: "BCR (Banca Comercială Română)",
    logoBg: "from-indigo-600 to-indigo-900",
    faculty: "Facultatea de Științe Economice și Gestiunea Afacerilor",
    description:
      "Căutăm un student sau proaspăt absolvent dornic să își înceapă cariera în finanțe. Vei asista echipa în analiza datelor economice, elaborarea rapoartelor financiare și previziuni bugetare.",
    requirements: [
      "Cunoștințe solide de contabilitate primară și analiză financiară",
      "Stăpânirea excelentă a instrumentelor din pachetul MS Excel (Pivot, VLOOKUP)",
      "Atenție deosebită la detalii și abilități analitice excelente",
      "Limba engleză la nivel avansat (scris și vorbit)",
    ],
    location: "București (Hibrid)",
    salary: "4.200 - 5.500 RON net",
    type: "Full-time",
    tags: ["Excel", "Corporate Finance", "Reporting", "Engleză"],
    date: "Acum 1 zi",
    compatibility: 90,
  },
  {
    id: "job-3",
    title: "Cloud Operations Intern",
    company: "NTT Data Romania",
    logoBg: "from-sky-400 to-blue-600",
    faculty: "Facultatea de Matematică și Informatică",
    description:
      "Vrei să înțelegi cum funcționează infrastructurile cloud moderne? Învață alături de mentori cu experiență în AWS și Azure cum se configurează, monitorizează și scalează serviciile online.",
    requirements: [
      "Cunoștințe teoretice despre rețele de calculatoare și sisteme de operare (Linux/Windows)",
      "Curiozitate legată de DevOps, Docker și virtualizare",
      "Disponibilitate de lucru 6 ore/zi pentru un stagiu de 3 luni plătite",
      "Capacitatea de a lucra eficient în echipă",
    ],
    location: "Cluj-Napoca (Remote)",
    salary: "3.200 RON net (6h/zi)",
    type: "Internship",
    tags: ["Linux", "Cloud", "AWS", "Docker"],
    date: "Acum 4 zile",
    compatibility: 88,
  },
  {
    id: "job-4",
    title: "Junior Legal Advisor",
    company: "Wolf Theiss",
    logoBg: "from-red-500 to-rose-700",
    faculty: "Facultatea de Drept",
    description:
      "Oferim oportunitatea de a lucra într-una dintre cele mai reputate firme de avocatură din Europa Centrală și de Est. Vei cerceta legislația și jurisprudența, redacta proiecte de documente legale și asista avocații asociați.",
    requirements: [
      "Student în an terminal sau absolvent de Drept",
      "Înțelegerea solidă a dreptului civil, comercial și a procedurii civile",
      "Abilități excelente de analiză și sinteză a textelor juridice",
      "Punctualitate, etică profesională și atenție la detalii",
    ],
    location: "București (On-site)",
    salary: "4.500 - 5.800 RON net",
    type: "Full-time",
    tags: ["Drept Civil", "Consulting", "Research", "Legal Drafting"],
    date: "Acum 3 zile",
    compatibility: 92,
  },
  {
    id: "job-5",
    title: "Junior Copywriter & Content Creator",
    company: "Editura Humanitas",
    logoBg: "from-amber-600 to-yellow-800",
    faculty: "Facultatea de Litere",
    description:
      "Ești pasionat de lectură și iubești cuvintele? Ajută-ne să creăm povești atractive pentru noile lansări de carte, newslettere, blog și canalele sociale ale editurii.",
    requirements: [
      "Excelente abilități de redactare și o stăpânire impecabilă a limbii române",
      "Cunoștințe generale din sfera culturală și literară din România",
      "Creativitate și capacitate de adaptare a stilului de scriere pentru diverse audiențe",
      "Experiență anterioară cu un blog personal sau activități de redacție reprezintă un avantaj",
    ],
    location: "București (Hibrid)",
    salary: "3.800 - 4.600 RON net",
    type: "Full-time",
    tags: ["Limba Română", "Creative Writing", "Social Media", "SEO"],
    date: "Acum 5 zile",
    compatibility: 95,
  },
  {
    id: "job-6",
    title: "Junior HR Generalist",
    company: "Mind-Space Solutions",
    logoBg: "from-purple-500 to-indigo-700",
    faculty: "Facultatea de Psihologie și Științe ale Educației",
    description:
      "Alătură-te echipei noastre de resurse umane. Vei fi implicat în procesul complet de selecție și recrutare, administrare de personal și în implementarea programelor de wellbeing din organizație.",
    requirements: [
      "Studii superioare finalizate sau în curs (Psihologie, Sociologie, Relații Publice)",
      "Abilități empatice pronunțate și capacitate crescută de ascultare activă",
      "Cunoașterea proceselor de bază din HR (recrutare, integrare)",
      "Disponibilitate pentru învățare continuă și flexibilitate",
    ],
    location: "Cluj-Napoca (Hibrid)",
    salary: "4.000 - 5.000 RON net",
    type: "Full-time",
    tags: ["Recrutare", "Psihologie", "Communication", "Wellbeing"],
    date: "Acum 6 zile",
    compatibility: 90,
  },
  {
    id: "job-7",
    title: "SQL & Data Analytics Intern",
    company: "KPMG Romania",
    logoBg: "from-emerald-500 to-teal-700",
    faculty: "Facultatea de Științe Economice și Gestiunea Afacerilor",
    description:
      "Experimentează activitatea de audit și consultanță de date la o companie Big Four. Vei ajuda echipele noastre să structureze baze de date complexe și să identifice modele statistice relevante.",
    requirements: [
      "Cunoștințe introductive de SQL (SELECT, JOIN, GROUP BY)",
      "Gândire logică și orientare spre rezolvarea de probleme cantitative",
      "Pasiune pentru date și vizualizarea lor (Power BI/Tableau)",
      "Seriozitate și capacitate de asimilare rapidă a feedback-ului",
    ],
    location: "București (Hibrid)",
    salary: "3.500 RON net",
    type: "Internship",
    tags: ["SQL", "Databases", "Data Analytics", "Power BI"],
    date: "Acum 1 săptămână",
    compatibility: 85,
  },
  {
    id: "job-8",
    title: "Python & Data Engineer Trainee",
    company: "UiPath Romania",
    logoBg: "from-orange-500 to-red-600",
    faculty: "Facultatea de Matematică și Informatică",
    description:
      "Începe-ți călătoria în inteligență artificială și automatizări software. Vei dezvolta scripturi de extragere a datelor în Python, integra servicii web API și configura modele simple de NLP.",
    requirements: [
      "Cunoștințe solide de limbaj Python (liste, dicționare, structuri repetitive)",
      "Înțelegerea noțiunilor fundamentale de structuri de date și algoritmi",
      "Familiaritate de bază cu baze de date relaționale (MySQL/PostgreSQL)",
      "Limba engleză la nivel mediu",
    ],
    location: "Cluj-Napoca (Hibrid)",
    salary: "5.000 - 6.500 RON net",
    type: "Full-time",
    tags: ["Python", "API", "Automation", "UiPath"],
    date: "Acum 3 zile",
    compatibility: 93,
  },
  {
    id: "job-9",
    title: "Legal Associate (Internship)",
    company: "Endava Legal Department",
    logoBg: "from-orange-600 to-indigo-800",
    faculty: "Facultatea de Drept",
    description:
      "Vrei să înțelegi cum funcționează conformitatea juridică într-o corporație globală de IT? Participă la un internship plătit unde vei asista la redactarea acordurilor de confidențialitate (NDA), analizarea contractelor comerciale și revizuirea politicilor interne.",
    requirements: [
      "Student în an terminal la Drept sau proaspăt absolvent",
      "Cunoașterea la nivel general a dreptului proprietății intelectuale și GDPR",
      "Engleză juridică excelentă (scris și vorbit)",
      "Proactivitate și abilități bune de organizare",
    ],
    location: "Cluj-Napoca (On-site)",
    salary: "3.500 RON net",
    type: "Internship",
    tags: ["GDPR", "NDA", "IT Law", "Engleză"],
    date: "Acum 1 zi",
    compatibility: 90,
  },
  {
    id: "job-10",
    title: "Translator & Localizer Specialist",
    company: "Electronic Arts (EA)",
    logoBg: "from-slate-700 to-rose-600",
    faculty: "Facultatea de Litere",
    description:
      "Contribuie la aducerea celor mai populare jocuri video pe piața din România. Vei traduce elemente de dialog, interfață grafică și materiale de marketing, menținând totodată coerența culturală și tonul original al povestirii.",
    requirements: [
      "Studii în derulare sau finalizate în Litere/Limbi Străine (Engleză - Română)",
      "Pasiune pentru jocuri video și cunoașterea terminologiei specifice gaming-ului",
      "Creativitate sporită în adaptarea expresiilor idiomatice",
      "Atenție deosebită la detalii lingvistice și gramaticale",
    ],
    location: "București (Remote)",
    salary: "4.000 - 4.800 RON net",
    type: "Full-time",
    tags: ["Traduceri", "Gaming", "Localization", "Limbi Străine"],
    date: "Acum 5 zile",
    compatibility: 92,
  },
  {
    id: "job-11",
    title: "Asistent Audit & Consultanță Fiscală",
    company: "PwC Romania",
    logoBg: "from-rose-800 to-amber-600",
    faculty: "Facultatea de Științe Economice și Gestiunea Afacerilor",
    description:
      "Ești pregătit să înțelegi secretele marilor afaceri? Lucrează cu portofoliul nostru diversificat de clienți, analizează tranzacțiile financiare ale acestora, verifică documente de conformitate fiscală și elaborează secțiuni din rapoartele de audit.",
    requirements: [
      "Cunoștințe solide de contabilitate românească și Standarde Internaționale (IFRS)",
      "Capacitatea de a procesa seturi mari de date în Excel",
      "Adaptabilitate sporită și bune abilități de prezentare",
      "Dorința de a obține certificări profesionale (ACCA/CCF)",
    ],
    location: "Cluj-Napoca (Hibrid)",
    salary: "4.500 - 5.800 RON net",
    type: "Full-time",
    tags: ["Audit", "IFRS", "Excel", "Fiscalitate"],
    date: "Acum 3 zile",
    compatibility: 92,
  },
  {
    id: "job-12",
    title: "UX Researcher Intern",
    company: "Cognizant Romania",
    logoBg: "from-cyan-600 to-blue-900",
    faculty: "Facultatea de Psihologie și Științe ale Educației",
    description:
      "Pune-ți în valoare cunoștințele de psihologie cognitivă. Vei proiecta și implementa teste de utilizare cu utilizatorii finali, analiza feedback-ul calitativ și genera rapoarte care să ghideze design-ul interfețelor aplicațiilor noastre.",
    requirements: [
      "Student în an terminal sau masterand în Psihologie sau Științe Sociale",
      "Înțelegerea metodelor de cercetare calitativă (interviuri, focus grupuri, teste cognitive)",
      "Abilități excelente de interpretare a datelor comportamentale",
      "Empatie ridicată și curiozitate pentru comportamentul uman online",
    ],
    location: "Cluj-Napoca (Hibrid)",
    salary: "3.500 RON net",
    type: "Internship",
    tags: [
      "UX Research",
      "Cognitive Psychology",
      "Interviews",
      "Data Analysis",
    ],
    date: "Acum 6 zile",
    compatibility: 95,
  },
  {
    id: "job-13",
    title: "Junior PR & Social Media Assistant",
    company: "TIFF (Transilvania Film)",
    logoBg: "from-red-600 to-black",
    faculty: "Facultatea de Litere",
    description:
      "Fii în inima celui mai mare festival de film din România! Vei ajuta echipa de relații publice să redacteze comunicate de presă, să mențină legătura cu jurnaliștii și să creeze campanii promoționale pe platformele sociale.",
    requirements: [
      "Student sau absolvent de Jurnalism, Litere sau Relații Publice",
      "Abilități de scriere creativă și capacitate excelentă de comunicare interpersonală",
      "Cunoașterea platformelor Instagram, TikTok și Facebook la nivel de business",
      "Entuziasm, flexibilitate și rezistență la stres în perioadele de festival",
    ],
    location: "Cluj-Napoca (Hibrid)",
    salary: "3.700 - 4.400 RON net",
    type: "Full-time",
    tags: ["PR", "Copywriting", "Film Festival", "TikTok"],
    date: "Acum 1 săptămână",
    compatibility: 90,
  },
  {
    id: "job-14",
    title: "Junior Counsel Counsel (Cabinet Avocat)",
    company: "Cabinet de Avocatură Mureșan & Asociații",
    logoBg: "from-amber-800 to-stone-900",
    faculty: "Facultatea de Drept",
    description:
      "Căutăm un coleg dornic de afirmare în avocatura de litigii și consultanță comercială. Vei efectua analize de dosare, redacta cereri de chemare în judecată, întâmpinări și concluzii scrise.",
    requirements: [
      "Licențiat în Drept, de preferat promovat al examenului de Barou",
      "Cunoașterea aprofundată a procedurii civile și a Codului Civil",
      "Gândire analicită și bune abilități oratorice",
      "Stăpânirea limbii engleze la nivel juridic",
    ],
    location: "Cluj-Napoca (On-site)",
    salary: "5.000 - 7.000 RON net",
    type: "Full-time",
    tags: ["Litigii", "Procedură Civilă", "Consulting", "Barou"],
    date: "Acum 2 săptămâni",
    compatibility: 95,
  },
  {
    id: "job-15",
    title: "Consilier Psihopedagog (Internship)",
    company: "Colegiul Național UBB",
    logoBg: "from-blue-800 to-indigo-950",
    faculty: "Facultatea de Psihologie și Științe ale Educației",
    description:
      "Stagiu plătit de consiliere dedicat elevilor de liceu. Vei lucra sub îndrumarea unui psiholog supervizor, vei asista la evaluări vocaționale și vei planifica ateliere de consiliere de grup pentru gestionarea anxietății de examen.",
    requirements: [
      "Masterand sau student an terminal în Psihologie / Științe ale Educației",
      "Cunoașterea instrumentelor de evaluare psihopedagogică",
      "Răbdare, tact pedagogic și abilități de conectare cu adolescenții",
      "Disponibilitate 4 ore pe zi pe durata semestrului",
    ],
    location: "Cluj-Napoca (On-site)",
    salary: "2.200 RON net (4h/zi)",
    type: "Internship",
    tags: ["Consiliere", "Pedagogie", "Vocational Testing", "Adolescents"],
    date: "Acum 4 zile",
    compatibility: 91,
  },
];

export function getJobs() {
  return mockJobs;
}

export function getApplications() {
  const saved = localStorage.getItem("ubb-ledger-apps");
  return saved ? JSON.parse(saved) : [];
}

export function saveApplications(apps) {
  localStorage.setItem("ubb-ledger-apps", JSON.stringify(apps));
}
